### ISSUE TITLE
Error: system cannot find the file specified

### ISSUE THREAD

**Issue by talenya** [MisterJimson/editProjFiles#3]
I installed LetMeEdit into my VS 2015:
    _Microsoft Visual Studio Professional 2015
    Version 14.0.25431.01 Update 3
    Microsoft .NET Framework
    Version 4.6.01055_

I restarted VS.

When I try to edit my .sln or a project file I get the error:

**The operation could not be completed. The system cannot find the file specified.**

The message does not include the file name of what can't be found (a shame).

Anyways, I can't edit my file.

**Comment by MisterJimson** [comment]
Strange.  The extension makes temp files while you edit them then saves them back into the original file. Perhaps it didn't have permission to create the files? I would expect VS to have permission.

**Comment by MisterJimson** [comment]
Maybe related to #5? Will close for now, reopen with more info if this is still a problem on 1.2.0.
