### ISSUE TITLE
VS2019 support

### ISSUE THREAD

**Issue by xperiandri** [MisterJimson/editProjFiles#6]
Please add

**Comment by MisterJimson** [comment]
Which projects types do you still use it for? VS 2017+ has the edit buttons for Net Core/Standard projects, or any projects that use the SDK style csproj.

**Comment by xperiandri** [comment]
Old project files
Actually extension installs but does not appear as context menu item

**Comment by xperiandri** [comment]
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by ransagy** [comment]
Just as a note - The extension in the Visual Studio Marketplace claims it does support 2019, But the installer doesn't add it to 2019, only 2017. The extension from the gallery appears in the search inside VS 2019, but doesn't actually install anything.

**Comment by VladislavAntonyuk** [comment]
https://github.com/MisterJimson/LetMeEdit/pull/7

**Comment by nvmkpk** [comment]
We still need this extension to edit the solution file.

**Comment by VladislavAntonyuk** [comment]
@nvmkpk, you can checkout my branch and build extension for VS2019. Looks like author is not going to update it (probably because VS2019 is not released yet)

**Comment by MisterJimson** [comment]
Done in 1.2.0.
