### ISSUE TITLE
It does cause unload and reload in visual studio when used for changing unity csproj files.

### ISSUE THREAD

**Issue by Uchiha1391** [MisterJimson/editProjFiles#9]
I use unity and when changing its csproj file through this extension it indeed caused reload of visual studio project.

**Comment by MisterJimson** [comment]
Does it automatically reload the project?

**Comment by Uchiha1391** [comment]
[](https://1drv.ms/v/s!AvoorJE76h5JlAuWiTE_HXWVFYZp?e=dgKBGp)
https://1drv.ms/v/s!AvoorJE76h5JlAuWiTE_HXWVFYZp?e=dgKBGp
check this little clip. you will see in the end when I try to edit csproj file it cause reloading of project.
Thanks for the reply though :)

**Comment by MisterJimson** [comment]
Thanks for the video.

Yes the project needs to reload after changes, this is intended. From the readme.

"This is a Visual Studio extention that lets you edit project and solution files without having to unload or close them first. **It will automatically reload when you save.**"

Sorry, but I am not aware of a way to get around that.
